export const TYPES = {
  DRIZZLE_TAG: 'DB_PROD',

  USER_ID: 'USER_ID',

  PERMISSION: {
    // SUPERUSER ARE ALLOWED TO DO ANYTHING
    // SUPERUSER IS ASSUMED TO HAVE ALL PERMISSIONS
    SUPERUSER: 'SUPERUSER',

    PRODUCT: {
      READ: 'PRODUCT_READ',
      CREATE: 'PRODUCT_CREATE',
      UPDATE: 'PRODUCT_UPDATE',
      ARCHIVE: 'PRODUCT_ARCHIVE',
    },
  },
};
